version: '3'

x-logging: &x-logging
  driver: journald
  options:
    tag: "{{.Name}}"

services:
  app:
    build: ./src
    ports:
      - 8080:8000
    logging: *x-logging
    environment:
      WAIT_HOSTS: db:5432
    depends_on:
      - db
      - manticore

  db:
    build: ./postgres
    volumes:
      - db_volume:/var/lib/postgresql/data/
    logging: *x-logging
    restart: always
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_PORT=5432
      - POSTGRES_SSLMODE=disable
    ports:
      - 5432:5432
    
  manticore:
    build: ./manticore
    restart: always
    logging: *x-logging
    volumes:
      - manticore_data:/var/lib/manticore/
      - manticore_logs:/var/log/manticore/
    ports:
      - 9306:9306

volumes:
  db_volume:
  manticore_data:
  manticore_logs:
